# Generated by Django 5.2.4 on 2025-08-05 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='user',
            new_name='user_id',
        ),
    ]
