# Generated by Django 5.2.4 on 2025-08-06 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization_app', '0002_rename_user_todo_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='user_id',
            new_name='user',
        ),
    ]
